FROM node:boron

RUN mkdir -p /app
RUN mkdir -p /app/api
RUN mkdir -p /app/node_modules
RUN mkdir -p /app/public
RUN mkdir -p /app/public/card
RUN mkdir -p /app/public/css
RUN mkdir -p /app/public/fonts
RUN mkdir -p /app/public/html
RUN mkdir -p /app/public/img
RUN mkdir -p /app/public/script

WORKDIR /app

COPY /api /app/api
COPY /node_modules /app/node_modules
COPY /package.json /app/package.json
COPY /public/css /app/public/css
COPY /public/fonts /app/public/fonts
COPY /public/html /app/public/html
COPY /public/img /app/public/img
COPY /public/script /app/public/script
COPY /server.js /app/server.js

# Set the running environment as production
ENV NODE_ENV production

# Executing defaults
CMD ["npm", "start"]

# Expose on specified network port
EXPOSE 80