FROM node:boron

RUN mkdir -p /app
RUN mkdir -p /app/api
RUN mkdir -p /app/node_modules
RUN mkdir -p /app/public

WORKDIR /app

COPY /api /app/api
COPY /node_modules /app/node_modules
COPY /package.json /app/package.json
COPY /public /app/public
COPY /server.js /app/server.js

# Set the running environment as production
ENV NODE_ENV production

# Executing defaults
CMD ["npm", "start"]

# Expose on specified network port
EXPOSE 80